baseURL = "https://www.filarmonicitrento.it/"
languageCode = "it"
title = "I Filarmonici di Trento"
publishDir = "docs"
relativeURLs = "False"

[params]
    name = "I Filarmonici di Trento"
    description = "Musica per Voi"
    email = ""
    phone = ""
    address = "c/o Soc. Filarmonica di Trento, Via G. Verdi 30, 38123, Trento"
    year = 2019
    avatar = "images/filarmonici.png"
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"


    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false


    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Organico"
    url = "/organico/"
    weight = 2

[[menu.main]]
    name = "Curriculum"
    url = "/curriculum/"
    weight = 3

[[menu.main]]
    name = "Collaborazioni"
    url = "/collaborazioni/"
    weight = 4

[[menu.main]]
    name = "Archivio"
    url = "/archivio/"
    weight = 5

[[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 6

[[menu.main]]
    name = "Contatti"
    url = "/contatti/"
    weight = 7

[[menu.main]]  
    name = "Parti"
    url = "https://www.filarmonicitrento.it/restricted/"
    weight = 7



[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/filarmonicitrento/"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fa-twitter-square"
    footer = false
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/orchestra_filarmoniciditrento"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fa-github"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:filarmonicitrento@gmail.com"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"

